### PR TITLE
Lower tracing version requirement

### PR DESCRIPTION
**Pull request by oli-obk**
It's not needed for venator, and rustc currently cannot update tracing due to performance regressions

### CODE REVIEW

**Comment by kmdreko** [comment]
A worthy change; much appreciated!

**Comment by kmdreko** [comment]
Unfortunately, it looks like I need to make some changes to get it to compile with `tracing 0.1.30`. I use some doc-hidden shenanigans because `Value` doesn't let you access anything without a `Field` and creating metadata via the normal means to get a valid field is not zero cost.

```
error[E0425]: cannot find value `CALLSITE` in this scope
   --> .../venator/src/attributes.rs:175:46
    |
175 |           static __CALLSITE: DefaultCallsite = callsite2!(
    |  ______________________________________________^
176 | |             name: "dummy",
177 | |             kind: Kind::SPAN,
178 | |             fields: dummy
179 | |         );
    | |_________^ not found in this scope

error[E0308]: mismatched types
   --> .../venator/src/attributes.rs:175:46
    |
175 |           static __CALLSITE: DefaultCallsite = callsite2!(
    |  ______________________________________________^
176 | |             name: "dummy",
177 | |             kind: Kind::SPAN,
178 | |             fields: dummy
179 | |         );
    | |_________^ expected `DefaultCallsite`, found `MacroCallsite`
```

I'll see if I can work something out though.

**Comment by kmdreko** [comment]
Okay, I have resolved the above issue (which is good to fix anyway), but there's another... The `venator` library supports `u128` and `i128` through the `Visit` trait. However, those methods don't exist until `v0.1.36` of `tracing`, so `v0.1.30` wouldn't work anyway.

I think I have a way to handle that.

**Comment by kmdreko** [comment]
I made a branch that you could try: [feat/downgrade-tracing-dep](https://github.com/kmdreko/venator/tree/feat/downgrade-tracing-dep) I feature-gated the 128-bit methods so with `default-features = false` it will go down to tracing `v0.1.0` if you wanted. Though its on that branch and not on `main` cuz I'm not 100% sure if that's how I want to handle it just yet.

**Comment by kmdreko** [comment]
I'm closing this PR since it needed more changes that I made in 6db96702e58fb816e196530931938fac19730158 and ff939e1d5363f5c34af888527293396b1cb057f9, but thank you very much for the contribution. Venator is all the more better for it. 

It will be incorporated into v1.0.1 when I publish it in a few days.

**Comment by kmdreko** [comment]
I'm closing this PR since it needed more changes that I made in 6db96702e58fb816e196530931938fac19730158 and ff939e1d5363f5c34af888527293396b1cb057f9, but thank you very much for the contribution. Venator is all the more better for it. 

It will be incorporated into v1.0.1 when I publish it in a few days.

**Comment by oli-obk** [comment]
Thank you! that was seriously above and beyond.
